version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.1.0
  aws-cli: circleci/aws-cli@1.4.1
jobs:
  test_backend:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers-legacy
        environment:
          RAILS_ENV: test
          DB_HOST: "127.0.0.1"
          TZ: Asia/Tokyo
      - image: circleci/mysql:5.7.32
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "~/repo/backend/Gemfile.lock" }}
            - gem-cache-v1-
      - run:
          name: Install bundler
          command: gem install bundler -v 2.2.15
          working_directory: backend
      - run:
          name: Which bundler?
          command: bundle -v
          working_directory: backend
      - run:
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
          working_directory: ~/repo/backend
      - save_cache:
          key: gem-cache-v1-{{ checksum "~/repo/backend/Gemfile.lock" }}
          paths:
            - ~/repo/backend/vendor/bundle

      # Database setup
      - run:
          command: bundle exec rails db:create
          working_directory: ~/repo/backend
      - run:
          command: bundle exec rails db:migrate
          working_directory: ~/repo/backend
      - run:
          command: bundle exec rails db:seed --trace
          working_directory: ~/repo/backend
      - run:
          name: create directory to store test results
          command: mkdir /tmp/test-results
          working_directory: ~/repo/backend

      # run tests
      - run:
          name: RSpec
          command: |
            bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings) \
              || (printf "====== RETRYING...\n\n\n"; bundle exec rspec --only-failures)
          working_directory: ~/repo/backend
      - run:
          name: Rubocop
          command: bundle exec rubocop
          working_directory: backend

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - store_artifacts:
          path: /home/circleci/repo/tmp/screenshots

  test_frontend:
    docker:
      - image: circleci/node:16
        environment:
          NODE_ENV: test
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/repo/frontend/package.json" }}

      - run:
          name: install-packages
          command: npm install
          working_directory: ~/repo/frontend
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "~/repo/frontend/package.json" }}

      - run:
          name: test
          command: npm run test
          working_directory: ~/repo/frontend

  build_and_push_image_backend:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          repo: "portfolio-backend"
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          path: "./backend"
          dockerfile: Dockerfile.prd

  build_and_push_image_frontend:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          repo: "portfolio-frontend"
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          path: "./frontend/"
          dockerfile: Dockerfile.prd

workflows:
  version: 2
  test:
    jobs:
      - test_backend:
          filters:
            branches:
              only: main
      - test_frontend:
          filters:
            branches:
              only: main
      - build_and_push_image_backend:
          requires:
            - test_frontend
            - test_backend
          filters:
            branches:
              only: main
      - build_and_push_image_frontend:
          requires:
            - test_frontend
            - test_backend
          filters:
            branches:
              only: main
      - aws-ecs/update-task-definition:
          family: portfolio-db-migrate
          # family: portfolio-db-seed
          # family: ${FAMILY_NAME_MIGRATE} # rails db:migrate用タスク定義名
          container-image-name-updates: "container=backend-container,tag=${CIRCLE_SHA1}"
          aws-region: AWS_REGION
          requires:
            - build_and_push_image_backend
          filters:
            branches:
              only: main

      - aws-ecs/run-task:
          cluster: portfolio-ecs-cluster
          # cluster: ${CLUSTER_NAME}
          task-definition: portfolio-db-migrate
          # task-definition: portfolio-db-seed
          # task-definition: ${TASK_MIGRATE}
          subnet-ids: subnet-07ee361eed5826853, subnet-089decef418e613f7
          assign-public-ip: ENABLED
          security-group-ids: "${MIGRATION_SECURITY_GROUP_ID}"
          requires:
            - aws-ecs/update-task-definition
          filters:
            branches:
              only: main

      - aws-ecs/run-task:
          cluster: portfolio-ecs-cluster
          task-definition: portfolio-db-seed
          subnet-ids: subnet-07ee361eed5826853, subnet-089decef418e613f7
          assign-public-ip: ENABLED
          security-group-ids: "${MIGRATION_SECURITY_GROUP_ID}"
          requires:
            - aws-ecs/update-task-definition
          filters:
            branches:
              only: main

      - aws-ecs/deploy-service-update:
          family: portfolio-frontend-task
          service-name: portfolio-frontend-ecs-service
          cluster-name: portfolio-ecs-cluster
          container-image-name-updates: "container=frontend-container,tag=${CIRCLE_SHA1}"
          requires:
            - build_and_push_image_frontend
          filters:
            branches:
              only: main
      - aws-ecs/deploy-service-update:
          requires:
            - build_and_push_image_frontend
            - build_and_push_image_backend
          family: portfolio-backend-task
          service-name: portfolio-backend-ecs-service
          cluster-name: portfolio-ecs-cluster
          container-image-name-updates: "container=backend-container,tag=${CIRCLE_SHA1}"
          filters:
            branches:
              only: main
